title : Totoro - Jekyll
description: 'A Modern Jekyll Theme'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-paginate]
permalink: /:year/:month/:title.html
